### PR TITLE
[RFC] use the right URL to api in dev mode

### PR DESCRIPTION
**Pull request by fansanelli**
Hello,

this is only compile tested, please review.

Thanks
Francesco

### CODE REVIEW

**Comment by frodrigo** [comment]
Thank you. It should be good test to use the API deployed on beta: `API_URL=http://beta.osmose.openstreetmap.fr`

**Comment by fansanelli** [comment]
> Thank you. It should be good test to use the API deployed on beta: `API_URL=http://beta.osmose.openstreetmap.fr`

I meant that I haven't tried the patch on a docker setup, but will do a test as soon as I can

**Comment by frodrigo** [comment]
Tested, and works for me. merged. Thank you.

**Comment by fansanelli** [comment]
Thanks for testing! Hope this will help the development

**Pull request merged**
