### PR TITLE
Allow menu to be resized by user

### PR DESCRIPTION
**Pull request by bagage**
This adds a resizeable icon in menu bottom right:

image

It is specially useful IMHO so that user can increase menu's width so that items are on a single line (which is language specific so maybe hard to achieve by default).

~~I couldn't test it because of #152 but it should be OK.~~ Tested on firefox/chromium linux is OK

### CODE REVIEW

**Comment by frodrigo** [comment]
Have you tested the tow commits?

**Comment by bagage** [comment]
yes

**Comment by frodrigo** [comment]
Ok. Thank you.
Require a manual deploy to osmose.osm.fr

**Comment by bagage** [comment]
Thanks @frodrigo for the quick merge!

**Comment by frodrigo** [comment]
deployed

**Pull request merged**
