### PR TITLE
Clarify 3100 handles several uses of land

### PR DESCRIPTION
**Pull request by Famlam**
Item 3100 contains:
- small woods
- small forests
- small farms
- small village greens

### CODE REVIEW

**Comment by frodrigo** [comment]
Ok, thank you.

**Comment by frodrigo** [comment]
Deployed. Now need to wait for translation update.

**Comment by Famlam** [comment]
> Now need to wait for translation update.

I suspect I can best cc @jocelynj for this? No rush :)

**Comment by jocelynj** [comment]
Translations have been updated - thanks for the notification.

**Comment by Famlam** [comment]
Hmm, Transifex doesn't show the new string yet for me 🤔

**Pull request merged**
