### PR TITLE
Rework the navbar with bootstrap.

### PR DESCRIPTION
**Pull request by francois2metz**
Since the osmose discussion this week end @sotmfr, I started some work to improve the UX/UI. 

My first take is the navbar. It's now use Bootstrap. Also the delay is now displayed with only a badge and a tooltip to display the details (green, orange, red).

I few thinks that I would like to discuss:

- Remove the link to the "Relation Analyzer", as there is always a 500
- A logo to display next to the project name (the one from twitter ?)

The result:

osmose-menu

### CODE REVIEW

**Comment by frodrigo** [comment]
Thank for the contribution.
I prefer to keep the delay displayed.

I will try your changes.

**Comment by francois2metz** [comment]
>  I prefer to keep the delay displayed.
Ok, I'll restore it.

**Comment by frodrigo** [comment]
I see few issues
- The user button have no the right style
- the rtl text is not on the right
image
- the menu is really big compared to the old one
- the old menu was more "reactive" than the new one, it's important to keep it usable on mobile
- the new menu require to click to open the menu

Note, detail pages already have to bootstrap menu.

**Comment by francois2metz** [comment]
Thanks for the review, I'll take a look.

**Comment by francois2metz** [comment]
>     * The user button have no the right style

Fixed. I will try to improve the dev mode on my machine
 
>     * the rtl text is not on the right

I learned that bootstrap 4 don't support rtl. I fixed that only for the dropdowns. 

Screenshot_2019-06-18 Osmose - نقشه

>     * the old menu was more "reactive" than the new one, it's important to keep it usable on mobile

It's usable in mobile using the hamburger button.

Screenshot_2019-06-18 Osmose - Map(1)

> I prefer to keep the delay displayed.

Screenshot_2019-06-18 Osmose - Map

>     * the menu is really big compared to the old one
>     * the new menu require to click to open the menu

This the look & feel of bootstrap. I prefer to not overwrite it.

**Comment by frodrigo** [comment]
Branche available on beta: http://beta.osmose.openstreetmap.fr
Open to comment.

**Comment by frodrigo** [comment]
There is display issue
image

I annoyed by this pull request. I see the technical benefit. But not the UX improvement.

**Pull request closed without merging**
