### PR TITLE
Add link to edit the osm object directly with id.

### PR DESCRIPTION
**Pull request by francois2metz**
Simliar to JOSM, ID allow to edit any osm objects with a special URL.

Screenshot_2019-06-16 Osmose - Map

### CODE REVIEW

**Comment by frodrigo** [comment]
Thank!

I think there is a typo issue, "ID" should be "iD", but "josm" also should be "JOSM". Maybe only change "ID" to "iD" to avoid "id"?

**Comment by frodrigo** [comment]
There is also other links to JOSM in other places than the popup.

**Comment by francois2metz** [comment]
I updated *ID* to *iD*. For JOSM links, I would like to delay it until I work on the new marker UI.

**Comment by frodrigo** [comment]
So, you are not interested in merging this PR for now ?

**Comment by francois2metz** [comment]
I'm interested! But updating the wording from josm to JOSM will be strange on some of the existing links (josm-zone for instance). Your call.

**Comment by frodrigo** [comment]
- Yes, keep josm in lower case.
- But, locate other JOSM links to add also iD link.

**Comment by francois2metz** [comment]
I cannot found other link to josm that could be used with iD. We cannot load objects or select multiple elements. The `osm-edit` could be renamed  `iD-edit` or `iD-zone` to match the `josm-zone` link.

**Comment by frodrigo** [comment]
> I cannot found other link to josm that could be used with iD. We cannot load objects or select multiple elements.

OK

> The osm-edit could be renamed iD-edit or iD-zone to match the josm-zone link.

No, the default edit on osm.org can be changed in the osm.org settings, and can be other editor than iD.

**Comment by frodrigo** [comment]
Marged. Thank.

**Pull request merged**
