### PR TITLE
Fix URL of link and guid of RSS

### PR DESCRIPTION
**Pull request by sim6**
I'm sorry my last changes are wrong :(

### CODE REVIEW

**Comment by jocelynj** [comment]
I'm not sure if it is still correct. Bottle escapes variables in template (see http://bottlepy.org/docs/dev/stpl.html#inline-expressions). Do we need to disable this escaping too ?

**Comment by sim6** [comment]
We can have & in the string and let Bottle escapes this and other HTML special characters, or we can have &amp; in the string and disable the escaping for all characters. What do you prefer?

**Comment by jocelynj** [comment]
I prefer your solution if we still need to escape the url. In any case, I will apply it, and if we need to not escape the url with bottle, we can replace {{url}} by {{!url}}

**Comment by sim6** [comment]
Thanks!

**Pull request merged**
