### PR TITLE
Update ru.po

### PR DESCRIPTION
**Pull request by tohaklim**
redact email

### CODE REVIEW

**Comment by frodrigo** [comment]
It come from transifex, we can't just delete it here.

cc @jocelynj

**Comment by jocelynj** [comment]
Didn't we already delete some emails earlier directly on .po files?

In any case, the email will re-appear next time @tohaklim do a translation, unless it is possible to configure transifex to not get emails.

**Comment by frodrigo** [comment]
Once we make clean, and transifex change all, back to the old way.

**Comment by jocelynj** [comment]
I'm applying the change, and we will check if it re-appears later.

**Pull request merged**
